// Code generated by sqlc. DO NOT EDIT.
// source: user.sql

package db

import (
	"context"
)

const createUser = `-- name: CreateUser :one
insert into users (username, hashed_pass, full_name, emain) values
($1, $2, $3, $4) returning username, hashed_pass, full_name, emain, pass_changed_at, created_at
`

type CreateUserParams struct {
	Username   string `json:"username"`
	HashedPass string `json:"hashed_pass"`
	FullName   string `json:"full_name"`
	Emain      string `json:"emain"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (Users, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Username,
		arg.HashedPass,
		arg.FullName,
		arg.Emain,
	)
	var i Users
	err := row.Scan(
		&i.Username,
		&i.HashedPass,
		&i.FullName,
		&i.Emain,
		&i.PassChangedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
select username, hashed_pass, full_name, emain, pass_changed_at, created_at from users
where username = $1 limit 1
`

func (q *Queries) GetUser(ctx context.Context, username string) (Users, error) {
	row := q.db.QueryRowContext(ctx, getUser, username)
	var i Users
	err := row.Scan(
		&i.Username,
		&i.HashedPass,
		&i.FullName,
		&i.Emain,
		&i.PassChangedAt,
		&i.CreatedAt,
	)
	return i, err
}
